---
title: "getting_to_know_infer"
author: "Chris Mann"
date: "27/01/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(glue)
library(tidymodels)
library(tidyverse)
```

Load data - using the gss dataset.
```{r}
# Load in the dataset
data(gss)

# Take a look at its structure
dplyr::glimpse(gss)
```

```{r}
gss
```
Check if there is a difference in income based on gender alone.
```{r}
gss_data <- gss %>% 
  mutate(income_range = income,
         income = str_remove(income, "\\s.+"),
         income = as.numeric(str_extract(income, "[0-9]+")))

gss_data%>% 
  group_by(sex) %>%
  summarise(mean_income = mean(income, na.rm = TRUE))
```
There is certainly a large-looking difference in the means.
```{r}
null_dist <- gss_data %>% 
  na.omit() %>% 
  specify(income ~ sex) %>% 
  hypothesise(null = "independence") %>%
  generate(reps = 1000, type = "permute") %>%
  calculate("diff in means", order = c("male", "female"))
head(null_dist)
```
```{r}
point_estimate <- gss_data %>%
  group_by(sex) %>% 
  summarise(mean_income = mean(income, na.rm = TRUE)) %>% 
  mutate(income_diff = mean_income - lag(mean_income)) %>% 
  na.omit() %>% 
  select(income_diff)
point_estimate
```


```{r}
null_dist %>%
  visualize() +
  shade_p_value(obs_stat = point_estimate, direction = "left")
```

```{r}
# get a two-tailed p-value
p_value <- null_dist %>%
  get_p_value(obs_stat = point_estimate, direction = "left")

p_value
```
```{r}
# start with the null distribution
null_dist %>%
  # calculate the confidence interval around the point estimate
  get_confidence_interval(point_estimate = point_estimate,
                          # at the 95% confidence level
                          level = .95,
                          # using the standard error
                          type = "se")
```


```{r}
gss %>%
  specify(college ~ partyid, success = "degree") %>%
  hypothesize(null = "independence")
```

```{r}
null_f_distn_theoretical <- gss %>%
   specify(age ~ partyid) %>%
   hypothesize(null = "independence") %>%
   calculate(stat = "F")
null_f_distn_theoretical
```

```{r}
F_hat <- gss %>% 
  specify(age ~ partyid) %>%
  calculate(stat = "F")
```

```{r}
visualize(null_f_distn_theoretical, method = "theoretical") +
  shade_p_value(obs_stat = F_hat, direction = "greater")
```

```{r}
null_f_distn <- gss %>%
   specify(age ~ partyid) %>%
   hypothesize(null = "independence") %>%
   generate(reps = 1000, type = "permute") %>%
   calculate(stat = "F")
```


```{r}
visualize(null_f_distn, method = "both") +
  shade_p_value(obs_stat = F_hat, direction = "greater")
```

