---
title: "infer_t_tests"
author: "Chris Mann"
date: "27/01/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidymodels)
library(tidyverse)
```

```{r}
theme_set(theme_light())
```


```{r}
# calculate the observed statistic
observed_statistic <- gss %>%
  specify(response = hours) %>%
  hypothesize(null = "point", mu = 40) %>%
  calculate(stat = "t")

observed_statistic
```

```{r}
# generate the null distribution
null_distribution_1_sample <- gss %>%
  specify(response = hours) %>%
  hypothesize(null = "point", mu = 40) %>%
  generate(reps = 1000, type = "bootstrap") %>%
  calculate(stat = "t")
null_distribution_1_sample
```
```{r}
# visualize the null distribution and test statistic!
null_distribution_1_sample %>%
  visualize() + 
  shade_p_value(observed_statistic,
                direction = "two-sided")
```

```{r}
# calculate the p value from the test statistic and null distribution
p_value_1_sample <- null_distribution_1_sample %>%
  get_p_value(obs_stat = observed_statistic,
              direction = "two-sided")

p_value_1_sample
```

```{r}
t_test(gss, response = hours, mu = 40)
```

```{r}
gss %>% 
  ggplot(aes(x = college, y = hours, fill = college)) +
  geom_boxplot()
```

```{r}
# calculate the observed statistic
observed_statistic <- gss %>%
  specify(hours ~ college) %>%
  calculate(stat = "t", order = c("degree", "no degree"))

observed_statistic
```

