---
title: "melborne_house_prices"
author: "Chris Mann"
date: "30/01/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
fpath <- "~/data/datasets/melb_data.csv"
dat <- readr::read_csv(fpath)
dat
```
```{r}
dat %>% 
  dplyr::select(!where(is.numeric))
```


```{r}
observed_indep_statistic <- dat %>% 
  infer::specify(Type ~ Suburb) %>% 
  infer::calculate(stat = "Chisq")
observed_indep_statistic
```

```{r}
# generate the null distribution using randomization
null_distribution_simulated <- dat %>% 
  dplyr::select(!where(is.numeric)) %>% 
  infer::specify(Type ~ Suburb) %>% 
  infer::calculate(stat = "Chisq") %>% 
  infer::hypothesize(null = "independence") %>%
  infer::generate(reps = 1000, type = "permute") %>%
  infer::calculate(stat = "Chisq")
null_distribution_simulated
```

```{r}
# generate the null distribution by theoretical approximation
null_distribution_theoretical <- gss %>%
  infer::specify(Type ~ Suburb)
  infer::hypothesize(null = "independence") %>%
  # note that we skip the generation step here!
  infer::calculate(stat = "Chisq")
```

